version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Use environment variable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Use environment variable
      POSTGRES_DB: ${POSTGRES_DB}  # Use environment variable
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map to the default PostgreSQL port
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
